### ISSUE TITLE
Markdown formatting not working correctly in param description fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/webapi#2]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=688
*date:* Tue Jun  3 18:46:58 2014
*author:* nickdos
 ---

See [http://api.ala.org.au/#ws9](http://api.ala.org.au/#ws9)

The ENV param has valid MD formatting (checked in MD viewer) but the text appears to get munged (newlines removed ?) so that some formatting gets lost. Looks like unordered lists don't work then stuff up subsequent bold formatting.

E.g. try

* list item 1
* **second** list item
* third item with **bold** text

**Comment by sbearcsiro** [comment]
@nickdos this should have been fixed by moving to the new server.  I'm going to close this issue but if it's not feel free to re-open.
