### ISSUE TITLE
Test and deploy Grails 3 version

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/webapi#22]
Production is still running version 1.0 with Grails 2 and BS2.

- [x] Update commonui version for latest 2019 skin.
- [x] Fix broken unit tests #23
- [x] Deploy the latest code to test site (and get someone to test it)
- [ ] release version of 2.0 
- [ ] prepare it for production release via CAB request

**Comment by Rita-C** [comment]
Test steps:
- go to https://api-test.ala.org.au, Web service API should display default "by category" list
- click "to list by application" link, display changes to "by application"
- expand/collapse a few API entries, detailed API information shown/hidden
- click on "Expand All" button, detailed API information shown for all
- click on "Collapse All" button, detailed API information disappeared

- go to https://api-test.ala.org.au/admin/apps

**Comment by nickdos** [comment]
Added test plan to Confluence https://confluence.csiro.au/display/ALASD/API+webapp

**Comment by ansell** [comment]
Testing complete for this https://github.com/AtlasOfLivingAustralia/cab/issues/15 , moving back to "TODO" on the board until #24 #25 #26 are fixed

**Comment by Rita-C** [comment]
#25 was fixed.
#24 and #26 are low priority tickets in backlog.

move this ticket back to QA with #25.

**Comment by nickdos** [comment]
Tested functionality for “delete webservice throws whitelable error page” - passed ✅
